### PR TITLE
425px Compatible

### PR DESCRIPTION
**Pull request by luwop**
hello, can you verify that these adjustments look good on your end. 

Thank you!

### CODE REVIEW

**Comment by asprgchong** [comment]
Hey Geno, thanks for this! 
A few things I would change: 
1. Enlarge the logo size from 425px onwards. (This would help me as well.) 
2. Try to lengthen the bus stops so that there is less grey space on the left. 
Screenshot 2024-06-16 at 2 51 21 PM
3. Shift the title to the left more (less margin-left) and increase the size of the text slightly. 
Screenshot 2024-06-16 at 2 53 37 PM
4. Try to enlarge the bottom artist cards so that there is less blank space at the bottom of the screen. 
5. Shift the mini map to the left more and add more margin-right to the images below of the Artist-details page.

**Review by asprgchong — CHANGES_REQUESTED** [review]
Great work! Just a few cosmetic changes. The formats for your media queries look great!

**Comment by luwop** [comment]
Here is the 425px view on the home page for my screen:

Screenshot 2024-06-17 at 8 13 28 PM

**Comment by luwop** [comment]
Here is the artist map for 425px

Screenshot 2024-06-17 at 8 18 58 PM

**Comment by luwop** [comment]
Screenshot 2024-06-17 at 8 21 59 PM

Here is the artist image container

**Pull request merged**
