### PR TITLE
Draft Navbar Component

### PR DESCRIPTION
**Pull request by luwop**

### CODE REVIEW

**Comment by luwop** [comment]
Here is my draft of the Navbar component.

**Comment by asprgchong** [comment]
Screenshot 2024-04-29 at 1 49 10 PM

Thanks for putting this together Geno, could you adjust the aspect ratio on the logo image? As it is currently stretching when I view it in the mobile viewer on inspect.

**Comment by luwop** [comment]
Hi, I've modified the aspect-ratio of the image. It shouldn't change sizes anymore. Please let me know if I need to add anything else.

**Comment by asprgchong** [comment]
Screenshot 2024-04-29 at 3 42 14 PM

Thanks for changing the aspect ratio! Looks great, Geno! 

Just a minor detail: would like to scale the entire nav bar down so that it doesn't clash with the title like the screenshot I made above. 
Once this is done, will merge the pr. Amazing work with the hamburger menu-- more than what was expected! Great work.

**Comment by luwop** [comment]
I've added some slight adjustments. How is this?

**Comment by asprgchong** [comment]
Looks great, Geno! Thanks for coding this up. Will merge now.

**Pull request merged**
